name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - if: node ./index.js
    - name: Team check
      run: echo "You're on the team!"
