name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Crew team checks
      if: node ./index.js crew
      run: echo "You're on the crew team!"
    - name: Others team checks
      if: node ./index.js others
      run: echo "You're on the others team!"
