name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: Crew team checks
      if: npm run team-check crew
      run: echo "You're on the crew team!"
    - name: Others team checks
      if: npm run team-check others
      run: echo "You're on the others team!"
